name: deploy website
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: checkout a copy of the repository
        uses: actions/checkout@master

      - name: deploy the website to djreed.com
        uses: wangyucode/sftp-upload-action@v1.1
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: ${{ secrets.PORT }}
          localDir: "site"
          remoteDir: ""
